# membersrvc node
membersrvc:
    image: hyperledger/fabric-membersrvc
    restart: unless-stopped
    ports:
      - "7054:7054"
    volumes:
      - "${PWD}/config/asset.yaml:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc.yaml"
    command: membersrvc  

# validating node as the root
vp0:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_PEER_NETWORKID=dev
    - CORE_LOGGING_LEVEL=debug #critical, error, warning, notice, info, debug
    # The following section enables pbft consensus
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops  
    - CORE_NOOPS_BLOCK_TIMEOUT=2s
    - CORE_NOOPS_BLOCK_WAIT=2s
  expose:
    - "7051"
    - "7052"
    - "7053"
  ports:
    - "7050:7050"
    - "7051:7051"
  volumes: &vol
    - /var/run/docker.sock:/var/run/docker.sock
  command:
      "sh -c 'sleep 1; peer node start'"
  links:
    - membersrvc

explorer:
    image: yeasy/blockchain-explorer
    hostname: explorer
    environment:
     - HYP_REST_ENDPOINT=http://vp0:7050
    expose:
     - "9090"
    ports:
     - "9090:9090"
    links:
     - vp0
